/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#a4ffb9',
        'primary-dim': '#00ed7e',
        'primary-fixed': '#00fd87',
        'primary-container': '#00fd87',
        'on-primary': '#006532',
        'on-primary-fixed': '#004621',
        'on-primary-container': '#005b2c',
        'on-primary-fixed-variant': '#006632',
        secondary: '#af88ff',
        'secondary-dim': '#8a4cfc',
        'secondary-container': '#6001d1',
        'secondary-fixed': '#dcc9ff',
        'secondary-fixed-dim': '#d0b8ff',
        'on-secondary': '#2b0065',
        'on-secondary-container': '#e1d0ff',
        'on-secondary-fixed': '#430097',
        'on-secondary-fixed-variant': '#6514d6',
        tertiary: '#699cff',
        'tertiary-dim': '#699cff',
        'tertiary-fixed': '#8ab0ff',
        'tertiary-fixed-dim': '#73a2ff',
        'tertiary-container': '#4388fd',
        'on-tertiary': '#001e4a',
        'on-tertiary-container': '#000311',
        'on-tertiary-fixed': '#00163b',
        'on-tertiary-fixed-variant': '#00377b',
        error: '#ff716c',
        'error-dim': '#d7383b',
        'error-container': '#9f0519',
        'on-error': '#490006',
        'on-error-container': '#ffa8a3',
        background: '#0e0e13',
        surface: '#0e0e13',
        'surface-dim': '#0e0e13',
        'surface-bright': '#2c2b33',
        'surface-tint': '#a4ffb9',
        'surface-variant': '#25252d',
        'surface-container-lowest': '#000000',
        'surface-container-low': '#131319',
        'surface-container': '#19191f',
        'surface-container-high': '#1f1f26',
        'surface-container-highest': '#25252d',
        'on-surface': '#f9f5fd',
        'on-surface-variant': '#acaab1',
        'on-background': '#f9f5fd',
        outline: '#76747b',
        'outline-variant': '#48474d',
        'inverse-surface': '#fcf8ff',
        'inverse-primary': '#006e37',
        'inverse-on-surface': '#55545b',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
}
