/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        'primary-dim': 'var(--color-primary-dim)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'primary-container': 'var(--color-primary-container)',
        'on-primary': 'var(--color-on-primary)',
        'on-primary-fixed': 'var(--color-on-primary-fixed)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        secondary: 'var(--color-secondary)',
        'secondary-dim': 'var(--color-secondary-dim)',
        'secondary-container': 'var(--color-secondary-container)',
        'secondary-fixed': 'var(--color-secondary-fixed)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
        'on-secondary': 'var(--color-on-secondary)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
        tertiary: 'var(--color-tertiary)',
        'tertiary-dim': 'var(--color-tertiary-dim)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        error: '#ff716c',
        'error-dim': '#d7383b',
        'error-container': '#9f0519',
        'on-error': '#490006',
        'on-error-container': '#ffa8a3',
        background: 'var(--color-background)',
        surface: 'var(--color-surface)',
        'surface-dim': 'var(--color-surface-dim)',
        'surface-bright': '#2c2b33',
        'surface-tint': 'var(--color-primary)',
        'surface-variant': 'var(--color-surface-variant)',
        'surface-container-lowest': 'var(--color-surface-lowest)',
        'surface-container-low': 'var(--color-surface-low)',
        'surface-container': 'var(--color-surface-container)',
        'surface-container-high': 'var(--color-surface-high)',
        'surface-container-highest': 'var(--color-surface-highest)',
        'on-surface': 'var(--color-on-surface)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'on-background': 'var(--color-on-background)',
        outline: 'var(--color-outline)',
        'outline-variant': 'var(--color-outline-variant)',
        'inverse-surface': '#fcf8ff',
        'inverse-primary': '#006e37',
        'inverse-on-surface': '#55545b',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
}
